import type { IconThemeMeta } from './types'

/*
  Material Icon Theme（PKief，MIT）。图标名是 @iconify-json/material-icon-theme 里的名字，
  scripts/build-icon-themes.mjs 按这张表把用到的图标抽成 sets/material.json，
  名字写错会在生成时报错。只挑 JS / TS 项目常见的那些。
*/

const folderNames: Record<string, string> = {
  src: 'folder-src', source: 'folder-src',
  lib: 'folder-lib', libs: 'folder-lib',
  dist: 'folder-dist', build: 'folder-dist', out: 'folder-dist', output: 'folder-dist',
  test: 'folder-test', tests: 'folder-test', __tests__: 'folder-test', spec: 'folder-test', e2e: 'folder-test',
  public: 'folder-public', static: 'folder-public', www: 'folder-public',
  docs: 'folder-docs', doc: 'folder-docs',
  config: 'folder-config', configs: 'folder-config', '.config': 'folder-config',
  scripts: 'folder-scripts', script: 'folder-scripts',
  assets: 'folder-resource', asset: 'folder-resource', resources: 'folder-resource',
  components: 'folder-components', component: 'folder-components',
  utils: 'folder-utils', util: 'folder-utils', utilities: 'folder-utils',
  helpers: 'folder-helper', helper: 'folder-helper',
  hooks: 'folder-hook', hook: 'folder-hook',
  types: 'folder-typescript', typings: 'folder-typescript', '@types': 'folder-typescript',
  examples: 'folder-examples', example: 'folder-examples', demo: 'folder-examples', demos: 'folder-examples',
  node_modules: 'folder-node',
  '.git': 'folder-git', '.github': 'folder-github', '.vscode': 'folder-vscode',
  images: 'folder-images', image: 'folder-images', img: 'folder-images', icons: 'folder-images',
  styles: 'folder-sass', style: 'folder-sass', css: 'folder-sass', scss: 'folder-sass',
  fonts: 'folder-font', font: 'folder-font',
  tmp: 'folder-temp', temp: 'folder-temp',
  tools: 'folder-tools', api: 'folder-api', app: 'folder-app',
  views: 'folder-views', view: 'folder-views', pages: 'folder-views', page: 'folder-views',
  layout: 'folder-layout', layouts: 'folder-layout',
  store: 'folder-store', stores: 'folder-store',
  context: 'folder-context', contexts: 'folder-context',
  constants: 'folder-constant', constant: 'folder-constant',
  i18n: 'folder-i18n', locales: 'folder-i18n', locale: 'folder-i18n', lang: 'folder-i18n',
  core: 'folder-core', shared: 'folder-shared', common: 'folder-shared',
  server: 'folder-server', client: 'folder-client', ui: 'folder-ui',
  plugins: 'folder-plugin', plugin: 'folder-plugin',
  middleware: 'folder-middleware', middlewares: 'folder-middleware',
  routes: 'folder-routes', router: 'folder-routes', routers: 'folder-routes',
  controllers: 'folder-controller', controller: 'folder-controller',
  db: 'folder-database', database: 'folder-database',
  mock: 'folder-mock', mocks: 'folder-mock', __mocks__: 'folder-mock',
  functions: 'folder-functions', coverage: 'folder-coverage', docker: 'folder-docker',
  template: 'folder-template', templates: 'folder-template',
  theme: 'folder-theme', themes: 'folder-theme',
  json: 'folder-json', packages: 'folder-packages', workers: 'folder-tasks',
  '.claude': 'folder-claude',
  other: 'folder-other',
}

const folderNamesExpanded = Object.fromEntries(
  Object.entries(folderNames).map(([k, v]) => [k, `${v}-open`])
)

export const material: IconThemeMeta = {
  id: 'material',
  label: 'Material',
  render: 'svg',
  rules: {
    file: 'document',
    // 默认目录就是上游的 folder / folder-open：单色的 blue grey，同 VS Code 里那个灰。
    // 别拿 folder-other 当默认 —— 那是「名字就叫 other 的目录」专用的那张，橙红色。
    // 这两个图标包里没有，由 scripts/build-icon-themes.mjs 从 folder-base 推出来
    folder: 'folder',
    folderExpanded: 'folder-open',
    fileNames: {
      'package.json': 'nodejs', '.nvmrc': 'nodejs', '.node-version': 'nodejs',
      'package-lock.json': 'npm', '.npmrc': 'npm',
      'pnpm-lock.yaml': 'pnpm', 'pnpm-workspace.yaml': 'pnpm',
      'yarn.lock': 'yarn', '.yarnrc': 'yarn', '.yarnrc.yml': 'yarn',
      'tsconfig.json': 'tsconfig', 'tsconfig.node.json': 'tsconfig', 'tsconfig.app.json': 'tsconfig',
      'tsconfig.base.json': 'tsconfig', 'jsconfig.json': 'tsconfig',
      '.gitignore': 'git', '.gitattributes': 'git', '.gitmodules': 'git',
      '.editorconfig': 'editorconfig',
      'readme.md': 'readme', 'readme': 'readme', 'readme.txt': 'readme',
      'license': 'license', 'license.md': 'license', 'license.txt': 'license',
      'dockerfile': 'docker', 'docker-compose.yml': 'docker', 'docker-compose.yaml': 'docker', '.dockerignore': 'docker',
      '.env': 'tune', '.env.local': 'tune', '.env.example': 'tune', '.env.development': 'tune', '.env.production': 'tune',
      'vite.config.ts': 'vite', 'vite.config.js': 'vite', 'vite.config.mts': 'vite', 'vite.config.mjs': 'vite',
      'vitest.config.ts': 'vitest', 'vitest.config.js': 'vitest', 'vitest.config.mts': 'vitest',
      'jest.config.js': 'jest', 'jest.config.ts': 'jest', 'jest.config.mjs': 'jest',
      '.prettierrc': 'prettier', '.prettierrc.json': 'prettier', '.prettierignore': 'prettier',
      'prettier.config.js': 'prettier', 'prettier.config.mjs': 'prettier',
      '.eslintrc': 'eslint', '.eslintrc.json': 'eslint', '.eslintrc.js': 'eslint', '.eslintignore': 'eslint',
      'eslint.config.js': 'eslint', 'eslint.config.mjs': 'eslint', 'eslint.config.ts': 'eslint',
      'vercel.json': 'vercel', 'netlify.toml': 'netlify',
      'settings.json': 'settings', 'extensions.json': 'settings', 'launch.json': 'settings',
    },
    fileExtensions: {
      js: 'javascript', mjs: 'javascript', cjs: 'javascript',
      jsx: 'react',
      ts: 'typescript', mts: 'typescript', cts: 'typescript',
      tsx: 'react-ts',
      'd.ts': 'typescript-def', 'd.mts': 'typescript-def', 'd.cts': 'typescript-def',
      'test.js': 'test-js', 'spec.js': 'test-js', 'test.mjs': 'test-js',
      'test.ts': 'test-ts', 'spec.ts': 'test-ts', 'test.mts': 'test-ts',
      'test.jsx': 'test-jsx', 'spec.jsx': 'test-jsx', 'test.tsx': 'test-jsx', 'spec.tsx': 'test-jsx',
      'js.map': 'javascript-map', 'mjs.map': 'javascript-map', 'cjs.map': 'javascript-map',
      json: 'json', jsonc: 'json', json5: 'json',
      html: 'html', htm: 'html',
      css: 'css', scss: 'sass', sass: 'sass', less: 'less',
      md: 'markdown', markdown: 'markdown', mdx: 'markdown',
      yml: 'yaml', yaml: 'yaml',
      xml: 'xml', svg: 'svg',
      sh: 'console', bash: 'console', zsh: 'console',
      sql: 'database',
      txt: 'document', log: 'log', env: 'tune', lock: 'lock',
      png: 'image', jpg: 'image', jpeg: 'image', gif: 'image', webp: 'image', ico: 'image', bmp: 'image', avif: 'image',
      woff: 'font', woff2: 'font', ttf: 'font', otf: 'font', eot: 'font',
      zip: 'zip', tar: 'zip', gz: 'zip', tgz: 'zip', '7z': 'zip', rar: 'zip',
      pdf: 'pdf',
      mp4: 'video', webm: 'video', mov: 'video',
      mp3: 'audio', wav: 'audio', ogg: 'audio', flac: 'audio',
    },
    languageIds: {
      javascript: 'javascript', typescript: 'typescript', json: 'json', html: 'html',
      css: 'css', scss: 'sass', less: 'less', markdown: 'markdown', yaml: 'yaml',
      xml: 'xml', shell: 'console', sql: 'database', plaintext: 'document',
    },
    folderNames,
    folderNamesExpanded,
  },
}
